### ISSUE TITLE
ghc 8.4: Can't get this to work

### ISSUE THREAD

**Issue by angerman** [serokell/serokell-util#64]
After fixing a few minor issues wrt. to `text-format` and `formatting` cross `universum` and using `o-clock` from GitHub, I keep running into:

```
src/Serokell/Util/Bench.hs:31:18: error:
        • Could not deduce (KnownRat
                              (Time.Rational.DivRat (1 Time.Rational.:% 1000000000) unit))
            arising from a use of ‘toUnit’
          from the context: KnownRat unit
            bound by the type signature for:
                       timeSpecToUnit :: forall (unit :: Time.Rational.Rat).
                                         KnownRat unit =>
                                         TimeSpec -> Time unit
            at src/Serokell/Util/Bench.hs:30:1-70
        • In the first argument of ‘(.)’, namely ‘toUnit @unit’
          In the expression: toUnit @unit . ns . fromIntegral . toNanoSecs
          In an equation for ‘timeSpecToUnit’:
              timeSpecToUnit = toUnit @unit . ns . fromIntegral . toNanoSecs
       |
    31 | timeSpecToUnit = toUnit @unit . ns . fromIntegral . toNanoSecs
       |                  ^^^^^^^^^^^^
```

with ghc-8.4, not so with ghc-8.2.

Now I've seen there are quite a few `#if ( __GLASGOW_HASKELL__ >= 804 )` conditionals in `o-clock`, but I'm unsure what the underlying reason might be. If anyone has seen this or can tell me how to fix it, I might be able to provide some PRs.

**Comment by ChShersh** [comment]
@angerman Thanks for your report! I'm not sure where this error come from. And yes, this might be hard to build and when `universum` itself doesn't build with GHC-8.4.1 :disappointed: See relevant issue (currently it's not decided what to do with `text-format` dependency):

* https://github.com/serokell/universum/issues/159

For now it's not clear to me why you see this error. But I think I can try to investigate it as well in near couple days (and releasing new major versions of `universum` and `o-clock` as well).

**Comment by vrom911** [comment]
@angerman I see that the problem is with the constraint `KnownRat unit ` for `8.4.1` version. You can try change it to `KnownDivRat Nanosecond unit`. I can't say for sure without checking but I guess it should work both for `8.2` and `8.4`.. 

You're welcome to make a PR for that it would be really helpful for transition to `8.4` :slightly_smiling_face:

**Comment by angerman** [comment]
@ChShersh I went ahead and dropped `text-format` from `universum` in favor of `formatting`. Primarily because `fmt` also depends on `formatting` now, and I wanted to keep the dependencies small.

@vrom911 Thanks that *seems* to have done the trick.

I'll need to do some more integration testing. And will send some PRs then.
